#ifndef _DNP_H
#define DNP_H


#define DNP_MIN_MESSAGE_SIZE_WITH_CRC				10
#define DNP_MAX_DATA_LINK_FRAME_SIZE_WITH_CRC		292
#define DNP_MAX_DATA_LINK_FRAME_SIZE_WITHOUT_CRC	255
#define DNP_MAX_APPLICATION_USER_BYTES_PER_FRAME	(255 - 5 - 1)	// Removes Datalink adn Transport Used Bytes
#define DNP_MAX_APPLICATION_FRAGMENT_WITHOUT_CRC	2048
#define DNP_MINIMUM_DATA_LINK_LENGTH_VALUE			5
#define DNP_TRANSPORT_SIZE							1		
#define DNP_DATA_LINK_LENGTH_WTHOUT_CRC				8
#define DNP_BYTES_PER_CRC							2

#define DNP_BROADCAST_ADDRESS_GENERIC			0xFFFF
#define DNP_BROADCAST_ADDRESS_CONFIRM			0xFFFE
#define DNP_BROADCAST_ADDRESS_DONT_CONFIRM		0xFFFD
#define DNP_SELF_ADDRESS						0xFFFC

#define DL_DIR 				0x80
#define DL_PRM 				0x40
#define DL_FCB 				0x20
#define DL_FCV 				0x10
#define DL_FUNCTION_CODE	0x0F

#define TH_FIN 	0x80
#define TH_FIR 	0x40

#define AC_FIR 	0x80
#define AC_FIN 	0x40
#define AC_CON	0x20
#define AC_UNS	0x10
#define AC_SEQ	0x0F

#define DL_LENGTH_OFFSET			2
#define DL_CONTROL_OCTET_OFFSET		3
#define DL_DESTINATION_OCTET_OFFSET	4
#define DL_SOURCE_OCTET_OFFSET		6

#define DLFUNC_RESETLINK				0x40
#define DLFUNC_TESTLINK					0x52	// Includes FCV bit
#define DLFUNC_CONFIRMED_USER_DATA		0x53	// Includes FCV bit
#define DLFUNC_UNCONFIRMED_USER_DATA	0x44
#define DLFUNC_REQUEST_LINK_STATUS		0x49

#define DLFUNC_ACK						0x00
#define DLFUNC_NACK						0x01
#define DLFUNC_LINK_STATUS				0x0B
#define DLFUNC_NOT_SUPPORTED			0x0F

#define DNP_TIME_LENGTH					6
#define DNP_NUMBER_OF_CLASSES			3
#define DNP_NO_EVENT_CLASS				-1

/*
 * Following are offsets into a received message with CRC octets removed
 */
#define MSG_OFFSET_TRANSPORT_CONTROL_OCTET					8	
#define MSG_OFFSET_APPLICATION_CONTROL_OCTET				9	
#define MSG_OFFSET_APPLICATION_FUNCTION_OCTET				10	
#define MSG_OFFSET_INTERNAL_INDICATIONS						11

#define DNP_APPLICATION_FUNCTION_CODE_CONFIRM				0
#define DNP_APPLICATION_FUNCTION_CODE_READ					1
#define DNP_APPLICATION_FUNCTION_CODE_WRITE					2
#define DNP_APPLICATION_FUNCTION_CODE_SELECT				3
#define DNP_APPLICATION_FUNCTION_CODE_OPERATE				4
#define DNP_APPLICATION_FUNCTION_CODE_DIRECT_OPERATE		5
#define DNP_APPLICATION_FUNCTION_CODE_DIRECT_OPERATE_NO_ACK	6
#define DNP_APPLICATION_FUNCTION_CODE_FREEZE				7
#define DNP_APPLICATION_FUNCTION_CODE_FREEZE_NR				8
#define DNP_APPLICATION_FUNCTION_CODE_FREEZE_AND_CLEAR		9
#define DNP_APPLICATION_FUNCTION_CODE_FREEZE_AND_CLEAR_NR	10
#define DNP_APPLICATION_FUNCTION_CODE_COLD_RESTART			13
#define DNP_APPLICATION_FUNCTION_ENABLE_UNSOLICITED			20
#define DNP_APPLICATION_FUNCTION_DISABLE_UNSOLICITED		21
#define DNP_APPLICATION_FUNCTION_CODE_ASSIGN_CLASS			22
#define DNP_APPLICATION_FUNCTION_CODE_DELAY_MEASUREMENT		23
#define DNP_APPLICATION_FUNCTION_CODE_RECORD_CURRENT_TIME	24
#define DNP_APPLICATION_FUNCTION_CODE_OPEN_FILE				25
#define DNP_APPLICATION_FUNCTION_CODE_CLOSE_FILE			26
#define DNP_APPLICATION_FUNCTION_CODE_DELETE_FILE			27
#define DNP_APPLICATION_FUNCTION_CODE_GET_FILE_INFO			28
#define DNP_APPLICATION_FUNCTION_CODE_ABORT_FILE			30
#define DNP_APPLICATION_FUNCTION_CODE_RESPONSE				129
#define DNP_APPLICATION_FUNCTION_CODE_UNSOLICITED_RESPONSE	130

#define DNP_WAITING_FOR_SOLICITED_EVENT_CONFIRMATION		0x01
#define DNP_WAITING_FOR_UNSOLICITED_EVENT_CONFIRMATION		0x02
#define DNP_WAITING_FOR_NULL_UNSOLCITED_ACK					0x04
#define DNP_WAITING_BROADCAST_IIN_ACK						0x08
#define DNP_GOT_A_DELAYED_READ								0x10
#define DNP_NOT_SAME_MESSAGE								0x20
#define DNP_MORE_DATA_TO_SEND								0x40

#define DNPOBJ_DEVICE_ATTRIBUTE				0
#define DNPOBJ_BINARY_INPUT					1 
#define DNPOBJ_BINARY_INPUT_EVENT			2 
#define DNPOBJ_DOUBLE_BINARY_INPUT			3 
#define DNPOBJ_DOUBLE_BINARY_INPUT_EVENT	4 
#define DNPOBJ_BINARY_OUTPUT_STATUS_INPUT	10
#define DNPOBJ_CROB							12 
#define DNPOBJ_RUNNING_COUNTER_INPUT		20 
#define DNPOBJ_FROZEN_COUNTER_INPUT			21 
#define DNPOBJ_RUNNING_COUNTER_INPUT_EVENT	22 
#define DNPOBJ_FROZEN_COUNTER_INPUT_EVENT	23 
#define DNPOBJ_ANALOG_INPUT					30 
#define DNPOBJ_ANALOG_INPUT_EVENT			32 
#define DNPOBJ_ANALOG_DEADBAND				34
#define DNPOBJ_ANALOG_OUTPUT_STATUS_INPUT	40
#define DNPOBJ_ANALOG_OUTPUT				41 
#define DNPOBJ_TIME_AND_DATE				50 
#define DNPOBJ_COMMON_TIME_OF_OCCURENCE		51
#define DNPOBJ_TIME_DELAY					52 
#define DNPOBJ_CLASS_DATA					60 
#define DNPOBJ_FILE_CONTROL					70
#define DNPOBJ_INTERNAL_INDICATIONS			80


#define DNPINPUT_HIGHEST_TYPE			41

#define DNPQUAL_START_STOP_1_OCTET		0
#define DNPQUAL_START_STOP_2_OCTETS		1
#define DNPQUAL_START_STOP_4_OCTETS		2
#define DNPQUAL_ALL						6
#define DNPQUAL_COUNT_1_OCTET			7
#define DNPQUAL_COUNT_2_OCTETS			8
#define DNPQUAL_COUNT_4_OCTETS			9

#define DNPQUAL_VARIABLE_LENGTH			0x5B

#define DNPQUAL_LIST_1_OCTET			0x17
#define DNPQUAL_LIST_2_OCTETS			0x28

#define IIN_BROADCAST			0x0001
#define IIN_CLASS_1				0x0002
#define IIN_CLASS_2				0x0004
#define IIN_CLASS_3				0x0008
#define IIN_NEED_TIME			0x0010
#define IIN_LOCAL_CONTROL		0x0020
#define IIN_DEVICE_TROUBLE		0x0040
#define IIN_DEVICE_RESTART		0x0080
#define IIN_BAD_FUNC_CODE		0x0100
#define IIN_OBJECT_UNKNOWN		0x0200
#define IIN_PARAMETER_ERROR		0x0400
#define IIN_BUFFER_OVERFLOW		0x0800
#define IIN_ALREADY_EXECUTING	0x1000
#define IIN_CONFIG_CORRUPT		0x2000

#define IIN_BROADCAST_INDEX				0
#define IIN_CLASS_1_INDEX				1
#define IIN_CLASS_2_INDEX				2
#define IIN_CLASS_3_INDEX				3
#define IIN_NEED_TIME_INDEX				4
#define IIN_LOCAL_CONTROL_INDEX			5
#define IIN_DEVICE_TROUBLE_INDEX		6
#define IIN_DEVICE_RESTART_INDEX		7
#define IIN_BAD_FUNC_CODE_INDEX			8
#define IIN_OBJECT_UNKNOWN_INDEX		9
#define IIN_PARAMETER_ERROR_INDEX		10
#define IIN_BUFFER_OVERFLOW_INDEX		11
#define IIN_ALREADY_EXECUTING_INDEX		12
#define IIN_CONFIG_CORRUPT_INDEX		13

#define DNP_DI_STATIC_VARIATION_PACKED				1
#define DNP_DI_STATIC_VARIATION_FLAG				2

#define DNP_DI_EVENT_VARIATION_FLAG					1
#define DNP_DI_EVENT_ABSOLUTE_TIME_VARIATION		2
#define DNP_DI_EVENT_RELATIVE_TIME_VARIATION		3

#define DNP_BOS_STATIC_VARIATION_FLAG				2

#define DNP_CROB_VARIATION_COMMAND					1

#define MAX_SIZE_GROUP_0_STRING	80

/*
 * Only Supported device attributes are listed below
 */

#define DNP_DEV_ATT_LOWEST							216
#define DNP_DEV_ATT_HIGHEST							252
#define DNP_DEV_ATT_SEND_INDEX_FOR_254				(DNP_DEV_ATT_HIGHEST - DNP_DEV_ATT_LOWEST + 1)
#define DNP_DEV_ATT_SEND_INDEX_FOR_255				(DNP_DEV_ATT_HIGHEST - DNP_DEV_ATT_LOWEST + 2)

#define DNP_DEV_ATT_VARIATION_MAX_CROB_PER_REQUEST			216	// MaxControlsPerRequest (Default: MAX_CONTROLS_PER_REQUEST)
#define DNP_DEV_ATT_VARIATION_LOCAL_TIMING_ACCURACY			217	// LocatTimingAccuracy (Default: LOCAL_TIMING_ACCURACY)
#define DNP_DEV_ATT_VARIATION_TIME_ACCURACY_DURATION		218 // TimeInvalidCountdown (Default: DEFAULT_TIME_INVALID_fREQUENCY)
#define DNP_DEV_ATT_VARIATION_SUPPORT_ANALOG_OUTPUT_EVENTS	219	// No
#define DNP_DEV_ATT_VARIATION_MAX_ANALOG_OUTPUT_INDEX		220	// Derived from point tables
#define DNP_DEV_ATT_VARIATION_NUMBER_OF_ANALOG_OUTPUTS		221 // Derived from point tables
#define DNP_DEV_ATT_VARIATION_SUPPORT_BINARY_OUTPUT_EVENTS	222	// No
#define DNP_DEV_ATT_VARIATION_MAX_BINARY_OUTPUT_INDEX		223 // Derived from point tables
#define DNP_DEV_ATT_VARIATION_NUMBER_OF_BINARY_OUTPUTS		224 // Derived from point tables
#define DNP_DEV_ATT_VARIATION_SUPPORT_FROZEN_COUNTER_EVENTS	225	// If subset level 3 or higher and couters defined
#define DNP_DEV_ATT_VARIATION_SUPPORT_FROZEN_COUNTERS		226	// Derived from point tables
#define DNP_DEV_ATT_VARIATION_SUPPORT_FOR_COUNTER_EVENTS	227	// Derived from point tables
#define DNP_DEV_ATT_VARIATION_MAX_COUNTER_INDEX				228	// Derived from point tables
#define DNP_DEV_ATT_VARIATION_NUMBER_OF_COUNTER_POINTS		229 // Derived from point tables
#define DNP_DEV_ATT_VARIATION_SUPPORT_FROZEN_ANALOGS		230	// No
#define DNP_DEV_ATT_VARIATION_SUPPORT_ANALOG_INPUT_EVENTS	231 // Derived from point tables. True if AI defined
#define DNP_DEV_ATT_VARIATION_MAX_ANALOG_INPUT_INDEX		232 // Derived from point tables
#define DNP_DEV_ATT_VARIATION_NUMBER_OF_ANALOG_INPUTS		233 // Derived from point tables
#define DNP_DEV_ATT_VARIATION_SUPPORT_DOUBLE_EVENTS			234 // Derived from point tables
#define DNP_DEV_ATT_VARIATION_MAX_DOUBLE_INDEX				235 // Derived from point tables
#define DNP_DEV_ATT_VARIATION_NUMBER_OF_DOUBLE_INPUTS		236 // Derived from point tables
#define DNP_DEV_ATT_VARIATION_SUPPORT_BINARY_INPUT_EVENTS	237
#define DNP_DEV_ATT_VARIATION_MAX_BINARY_INPUT_INDEX		238
#define DNP_DEV_ATT_VARIATION_NUMBER_BINARY_INPUTS			239
#define DNP_DEV_ATT_VARIATION_MAX_TRANSMIT_FRAGMENT_SIZE	240	// 2048
#define DNP_DEV_ATT_VARIATION_MAX_RECEIVE_FRAGMENT_SIZE		241	// 249
#define DNP_DEV_ATT_VARIATION_SOFTWARE_VERSION_NUMBER		242 // Software_Version (Default: SOFTWARE_VERSION)
#define DNP_DEV_ATT_VARIATION_HARDWARE_VERSION				243	// Hardware_Version (Default: HARDWARE_VERSION)
#define DNP_DEV_ATT_VARIATION_INSTALLED_LOCATION			245	// Installed_Locatio (Default: INSTALLED_LOCATION)
#define DNP_DEV_ATT_VARIATION_USER_ID						246	// User_id (Default: USER_ID)
#define DNP_DEV_ATT_VARIATION_DEVICE_NAME					247 // Device_Name (Default: DEVICE_NAME)
#define DNP_DEV_ATT_VARIATION_DEVICE_SERIAL_NUMBER			248	// Serial_Number (Default: SERIAL_NUMBER)
#define DNP_DEV_ATT_VARIATION_DNP_SUBSET					249 // SubsetLevel (Default: DEFAULT_SUBSET_LEVEL)
#define DNP_DEV_ATT_VARIATION_DEVICE_PRODUCT_NAME			250 // Product_Name (Default: PRODUCT_NAME)
#define DNP_DEV_ATT_VARIATION_MANUFACTURERS_NAME			252 // Manufacturers_Name (Default: MANUFACTURERS_NAME)


#define DNP_DEV_ATT_VARIATION_READ_ALL_ATTRIBUTES			254
#define DNP_DEV_ATT_VARIATION_READ_ATTRIBUTE_LIST			255

#define DNP_DEV_ATT_DATA_TYPE_STRING						1
#define DNP_DEV_ATT_DATA_TYPE_UINT							2

#define DNP_DEV_ATTRIBUTE_READ_ONLY							0

#define DNP_VARIATION_ANY							0

#define DNP_AI_STATIC_VARIATION_FLAG_32_BIT			1
#define DNP_AI_STATIC_VARIATION_FLAG_16_BIT			2
#define DNP_AI_STATIC_VARIATION_NOFLAG_32_BIT		3
#define DNP_AI_STATIC_VARIATION_NOFLAG_16_BIT		4
#define DNP_AI_STATIC_VARIATION_FLAG_FLOAT			5

#define DNP_AI_EVENT_VARIATION_32_BIT				1
#define DNP_AI_EVENT_VARIATION_16_BIT				2
#define DNP_AI_EVENT_VARIATION_TIME_32_BIT			3
#define DNP_AI_EVENT_VARIATION_TIME_16_BIT			4
#define DNP_AI_EVENT_VARIATION_FLOAT				5
#define DNP_AI_EVENT_VARIATION_TIME_FLOAT			7

#define DNP_AI_DEADBAND_VARIATION_16_BIT			1
#define DNP_AI_DEADBAND_VARIATION_32_BIT			2
#define DNP_AI_DEADBAND_VARIATION_FLOAT				3

#define DNP_RC_STATIC_VARIATION_FLAG_32_BIT			1
#define DNP_RC_STATIC_VARIATION_FLAG_16_BIT			2
#define DNP_RC_STATIC_VARIATION_NOFLAG_32_BIT		5
#define DNP_RC_STATIC_VARIATION_NOFLAG_16_BIT		6

#define DNP_RC_EVENT_VARIATION_32_BIT				1
#define DNP_RC_EVENT_VARIATION_16_BIT				2
#define DNP_RC_EVENT_VARIATION_TIME_32_BIT			5
#define DNP_RC_EVENT_VARIATION_TIME_16_BIT			6

#define DNP_FC_STATIC_VARIATION_FLAG_32_BIT			1
#define DNP_FC_STATIC_VARIATION_FLAG_16_BIT			2
#define DNP_FC_STATIC_VARIATION_TIME_32_BIT			5
#define DNP_FC_STATIC_VARIATION_TIME_16_BIT			6
#define DNP_FC_STATIC_VARIATION_NOFLAG_32_BIT		9
#define DNP_FC_STATIC_VARIATION_NOFLAG_16_BIT		10

#define DNP_FC_EVENT_VARIATION_32_BIT				1
#define DNP_FC_EVENT_VARIATION_16_BIT				2
#define DNP_FC_EVENT_VARIATION_TIME_32_BIT			5
#define DNP_FC_EVENT_VARIATION_TIME_16_BIT			6

#define DNP_AOS_STATIC_VARIATION_32_BIT				1
#define DNP_AOS_STATIC_VARIATION_16_BIT				2
#define DNP_AOS_STATIC_VARIATION_FLOAT				3

#define DNP_AO_VARIATION_32_BIT						1
#define DNP_AO_VARIATION_16_BIT						2
#define DNP_AO_VARIATION_FLOAT						3

#define DNP_TDATE_VARIATION_ABSOLUTE				1
#define DNP_TDATE_VARIATION_AT_LAST_RECORDED		3

#define DNP_CTO_VARIATION_SYNCHRONIZED				1
#define DNP_CTO_VARIATION_UNSYNCHRONIZED			2

#define DNP_TDURATION_VARIATION_FINE				2

#define DNP_FILE_VARIATION_IDENTIFIER				1
#define DNP_FILE_VARIATION_AUTHENTICATION			2
#define DNP_FILE_VARIATION_COMMAND					3
#define DNP_FILE_VARIATION_COMMAND_STATUS			4
#define DNP_FILE_VARIATION_TRANSPORT				5
#define DNP_FILE_VARIATION_TRANSPORT_STATUS			6
#define DNP_FILE_VARIATION_DESCRIPTOR				7
#define DNP_FILE_VARIATION_SPECIFICATION_STRING		8

#define DNP_FILE_OPERATIONAL_MODE_READ				1
#define DNP_FILE_OPERATIONAL_MODE_WRITE				2
#define DNP_FILE_OPERATIONAL_MODE_APPEND			3

#define DNP_FILE_STATUS_CODE_SUCCESS				0
#define DNP_FILE_STATUS_CODE_INVALID_MODE			2
#define DNP_FILE_STATUS_CODE_FILE_NOT_FOUND			3
#define DNP_FILE_STATUS_CODE_FILE_LOCKED			4
#define DNP_FILE_STATUS_CODE_TOO_MANY_OPEN			5
#define DNP_FILE_STATUS_CODE_INVALID_HANDLE			6
#define DNP_FILE_STATUS_CODE_CANNOT_ABORT			9
#define DNP_FILE_STATUS_CODE_NOT_OPENED				16
#define DNP_FILE_STATUS_CODE_FATAL					19
#define DNP_FILE_STATUS_CODE_BLOCK_SEQ				20

#define DNP_FILE_LAST_BLOCK						0x80000000

#define DNP_CONTROL_STATUS_CODE_SUCCESS				0
#define DNP_CONTROL_STATUS_CODE_TIMEOUT				1
#define DNP_CONTROL_STATUS_CODE_NO_SELECT			2
#define DNP_CONTROL_STATUS_CODE_FORMAT_ERROR		3
#define DNP_CONTROL_STATUS_CODE_NOT_SUPPORTED		4
#define DNP_CONTROL_STATUS_LOCAL_MODE				7
#define DNP_CONTROL_STATUS_CODE_TOO_MANY_OBJECTS	8

#define ABSOLUTE_MAX_CONTROLS_PER_REQUEST			20

#define DNP_CC_PULSE_ON								1
#define DNP_CC_TRIP									0x81
#define DNP_CC_CLOSE								0x41
#define DNP_CC_LATCH_ON								3
#define DNP_CC_LATCH_OFF							4

#define DNP_POINT_FLAG_ONLINE					0x01
#define DNP_POINT_FLAG_RESTART					0x02
#define DNP_POINT_FLAG_OVERRANGE				0x20
#define DNP_POINT_FLAG_DISCONTINUITY			0x40

#define UNSOLICITED_POSSIBLE					0x01
#define UNSOLICITED_STATE_INITIAL_NULL			0x02

#define UNSOLICITED_DEGRADED_COUNT				50	// Start degraded timer after these failures

#define ANY_ERR_IIN_SET(iin)  (iin & (IIN_PARAMETER_ERROR | IIN_BAD_FUNC_CODE | IIN_OBJECT_UNKNOWN))
#define VALID_CONTROL_CODE(cc) ((cc == DNP_CC_PULSE_ON) || (cc == DNP_CC_TRIP) || (cc == DNP_CC_CLOSE) || (cc == DNP_CC_LATCH_ON) || (cc == DNP_CC_LATCH_OFF))

#define SET_IIN(val) (InternalIndications |= val)
#define CLEAR_IIN(val) (InternalIndications &= ~(val))
#define IS_IIN_SET(val) (InternalIndications & val)

typedef struct
{
	int16_t FileNameStringOffset;
	int16_t FileNameStringSize;
	char TimeOfCreation[6];
	int16_t Permissions;
	int32_t AuthenticationKey;
	int32_t FileSize;
	int16_t OperationalMode;
	int16_t MaximumBlockSize;
	int16_t RequestID;
} FileCommand_t;				// Variation 3

typedef struct
{
	char FileNameStringOffset[2];
	char FileNameStringSize[2];
	char FileType[2];
	char FileSize[4];
	char TimeOfCreation[6];
	char Permissions[2];
	char RequestID[2];
} FileDescriptor_t;				// Variation 7

typedef struct
{
	char FileHandle[4];			// Takes care of Endian 	
	char FileSize[4];
	char MaximumBlockSize[2];
	char RequestID[2];
	char StatusCode;
} FileCommandStatus_t;				// Variation 4

typedef struct
{
	int32_t FileHandle;
	int32_t BlockNumber;
} FileTransport_t;				// Variation 5

typedef struct
{
	char FileHandle[4];
	char BlockNumber[4];
	char StatusCode;
//  char Fil informatio[...]
} FileTransportStatus_t;		// Variation 6

#define FILE_HANDLE_FOR_READ						1
#define FILE_HANDLE_FOR_WRITE						2
#define MAX_FILE_NAME_SIZE							100
#define FILE_OPTIONS_ALLOW_READ						0x01
#define FILE_OPTIONS_ALLOW_DELETE					0x02
#define FILE_OPTIONS_ALLOW_WRITE					0x04


#define FILE_MAXIMUM_BLOCK_SIZE						230


#endif
